"""Real PostgreSQL and local files; generated bytes test storage, not decoding."""

import hashlib
import os
import subprocess
import sys
import time
from uuid import UUID

import pytest
from media_queue import RecordingMediaQueue
from psycopg.types.json import Jsonb
from test_registry import enroll, frame

from central.coordination import Coordinator
from central.execution_repository import PostgresExecutionRepository
from central.media_repository import MediaRepository, StoreLimits
from central.media_store import MediaStore, MediaStoreError
from central.registry import RegistryError
from contracts.models import Calibration, Layer, Plan, Variant
from media.models import OriginalAsset, SourceSpec
from media.prepare import BuildIdentity, PreparedMedia

RECIPE = "e" * 64
ORIGINAL = b"public synthetic original bytes"
VARIANT = b"public synthetic prepared bytes"


@pytest.fixture
def storage(registry, tmp_path):
    repository = MediaRepository(registry.db, registry.clock, StoreLimits(
        max_bytes=10000, max_original_bytes=1000, max_image_bytes=1000, max_video_bytes=2000),
        queue=RecordingMediaQueue())
    repository.set_recipe(RECIPE)
    return MediaStore(
        repository,
        tmp_path / "media",
        execution=PostgresExecutionRepository(),
    )


def queued(storage, number=1, *, original=ORIGINAL):
    asset = OriginalAsset(connection_id="fixture", upstream_id=str(UUID(int=number)),
                          original_sha1=hashlib.sha1(original).hexdigest(), kind="image",
                          raw_width=1080, raw_height=1920, orientation=1, captured_at=1000,
                          file_size=len(original))
    with storage.repository.transaction() as conn:
        conn.execute("INSERT INTO asset_revisions VALUES(%s,%s,1000,1000)",
                     (asset.asset_id, Jsonb(asset.model_dump(mode="json"))))
        conn.execute("INSERT INTO media_jobs(id,asset_id,recipe_id,state,earliest_start,updated_at) "
                     "VALUES(%s,%s,%s,'queued',1000,1000)", (f"job-{number}", asset.asset_id, RECIPE))
    return asset


def staged(storage, number=1, *, original=ORIGINAL, derivative=VARIANT):
    queued(storage, number, original=original)
    lease = storage.repository.claim_job()
    assert lease is not None
    paths = storage.staging(lease)
    paths.original.write_bytes(original)
    paths.variant.write_bytes(derivative)
    variant = Variant(sha256=hashlib.sha256(derivative).hexdigest(), size=len(derivative),
                      media_type="image/jpeg", width=1080, height=1920)
    build = BuildIdentity(preparation_sha256="a" * 64, ffmpeg_sha256="b" * 64, ffprobe_sha256="c" * 64,
                          ffmpeg_version="synthetic", ffprobe_version="synthetic", python_version="synthetic",
                          pillow_version="synthetic", littlecms_version="synthetic", jpeg_version="synthetic",
                          zlib_version="synthetic", platform="synthetic", memory_limit_enforced=False)
    prepared = PreparedMedia(path=paths.variant, variant=variant, original_sha256=hashlib.sha256(original).hexdigest(),
                             recipe_id=RECIPE, build=build)
    return lease, paths, prepared


def row(storage, table, key, value):
    assert (table, key) in {("media_jobs", "id"), ("media_blobs", "digest")}
    with storage.db.transaction() as conn:
        return conn.execute(f"SELECT * FROM {table} WHERE {key}=%s", (value,)).fetchone()


def ready(storage, number=1, **kwargs):
    lease, paths, prepared = staged(storage, number, **kwargs)
    assert storage.publish(lease, prepared) == prepared.variant
    return lease, paths, prepared


def grant(storage, registry, variant, *, secured=False):
    player, key, _ = enroll(registry)
    frame(registry, "portrait")
    registry.bind("portrait", player["player_id"], "HDMI-A-1", expected_generation=0)
    registry.calibrate("portrait", "commit", 1, Calibration(), expected_generation=1)
    binding = registry.bindings_for(player["player_id"], 1)[0]
    layer = Layer(assignment_id="assignment", run_id="run", output_id=binding.output_id,
                  frame_id=binding.frame_id, binding_generation=binding.generation,
                  start=1000, end=1200, media_origin=1000, variant=variant)
    plan = Plan(plan_id="plan", revision=1, player_id=player["player_id"], authority_epoch=1,
                issued_at=1000, valid_from=1000, valid_until=1200, bindings=(binding,), layers=(layer,))
    with storage.repository.transaction() as conn:
        if secured:
            conn.execute("INSERT INTO assignment_locks VALUES(%s,1,%s,%s,1000,1200)",
                         (player["player_id"], layer.assignment_id, Jsonb(layer.model_dump(mode="json"))))
            conn.execute("INSERT INTO media_references VALUES(%s,%s,1200)",
                         (f"secured:{player['player_id']}:1:{layer.assignment_id}", variant.sha256))
        else:
            Coordinator(storage.db, storage.clock)._offer(conn, plan, {layer.assignment_id: "group"})
    return player, key, plan


def test_exclusive_worker_lock_and_writer_only_methods(storage):
    with pytest.raises(MediaStoreError, match="writer_required"):
        storage.recover()
    with storage.worker_lock():
        contender = MediaStore(storage.repository, storage.root)
        with pytest.raises(MediaStoreError, match="writer_active"):
            with contender.worker_lock():
                pytest.fail("second writer entered")
    with MediaStore(storage.repository, storage.root).worker_lock():
        pass


def test_reservation_exists_before_staging_and_stale_attempt_cannot_create_files(storage):
    with storage.worker_lock():
        queued(storage)
        lease = storage.repository.claim_job()
        assert storage.repository.health()["accounted_bytes"] == 2000
        assert not (storage.root / "staging" / lease.job_id).exists()
        bogus = lease.model_copy(update={"attempt_token": "other-attempt"})
        with pytest.raises(RegistryError, match="stale_job"):
            storage.staging(bogus)
        assert not (storage.root / "staging" / lease.job_id).exists()
        paths = storage.staging(lease)
        assert paths.directory.stat().st_mode & 0o777 == 0o700
        storage.fail(lease, "fixture_failure")
        assert storage.repository.health()["accounted_bytes"] == 0


def test_publish_durable_bytes_exact_journal_and_catalog(storage):
    with storage.worker_lock():
        lease, paths, prepared = staged(storage)
        storage.repository.configure_source(SourceSpec(source_ref="library:1", connection_ref="fixture"))
        with storage.repository.transaction() as conn:
            conn.execute("UPDATE media_sources SET status='ok'")
            conn.execute("INSERT INTO source_members VALUES('library:1',%s)", (lease.asset.asset_id,))
        storage.publish(lease, prepared)
        assert not paths.directory.exists()
        assert (storage.root / "blobs" / prepared.variant.sha256).read_bytes() == VARIANT
        job = row(storage, "media_jobs", "id", lease.job_id)
        assert job["state"] == "ready" and job["reserved_bytes"] == 0 and job["cleanup_state"] is None
        assert job["result"]["original_sha1"] == lease.asset.original_sha1
        assert job["result"]["build"] == prepared.build.model_dump(mode="json")
        assert storage.repository.health()["accounted_bytes"] == len(VARIANT)
        with storage.db.transaction() as conn:
            snapshot = conn.execute("SELECT snapshot FROM catalog_snapshots WHERE source_ref='library:1'").fetchone()["snapshot"]
        assert snapshot["candidates"][0]["variant"] == prepared.variant.model_dump(mode="json")


def test_duplicate_digest_is_verified_and_counted_once(storage):
    with storage.worker_lock():
        _, _, first = ready(storage)
        second, paths, prepared = staged(storage, 2, original=b"different public original")
        storage.publish(second, prepared)
        assert not paths.directory.exists()
        assert first.variant == prepared.variant
        assert storage.repository.health()["accounted_bytes"] == len(VARIANT)
        assert row(storage, "media_jobs", "id", second.job_id)["state"] == "ready"


@pytest.mark.parametrize("fault", ["recipe", "original", "digest", "path", "stale"])
def test_publication_mismatch_never_exposes_ready_bytes(storage, fault):
    with storage.worker_lock():
        lease, paths, prepared = staged(storage)
        if fault == "recipe":
            prepared = prepared.model_copy(update={"recipe_id": "f" * 64})
        elif fault == "original":
            paths.original.write_bytes(b"changed public original")
        elif fault == "digest":
            paths.variant.write_bytes(b"changed public derivative")
        elif fault == "path":
            prepared = prepared.model_copy(update={"path": storage.root / "other"})
        else:
            lease = lease.model_copy(update={"attempt_token": "wrong"})
        with pytest.raises(RegistryError):
            storage.publish(lease, prepared)
        with storage.db.transaction() as conn:
            assert conn.execute("SELECT count(*) AS n FROM media_blobs").fetchone()["n"] == 0
        assert storage.repository.health()["accounted_bytes"] == 2000


class Crash(BaseException):
    pass


@pytest.mark.parametrize("boundary", ["before_rename", "after_rename", "after_cleanup"])
def test_restart_recovers_actual_publication_files_across_journal_boundaries(storage, monkeypatch, boundary):
    with storage.worker_lock():
        lease, paths, prepared = staged(storage)
        if boundary == "before_rename":
            monkeypatch.setattr(storage, "_rename", lambda *_: (_ for _ in ()).throw(Crash()))
        else:
            real_fsync = storage._fsync_directory
            def crash(path):
                real_fsync(path)
                trigger = paths.directory if boundary == "after_rename" else paths.directory.parent
                if path == trigger:
                    raise Crash()
            monkeypatch.setattr(storage, "_fsync_directory", crash)
        with pytest.raises(Crash):
            storage.publish(lease, prepared)
        journal = row(storage, "media_jobs", "id", lease.job_id)
        assert journal["state"] in ("publishing", "cleanup")
        assert journal["reserved_bytes"] + len(VARIANT) == 2000
    restarted = MediaStore(storage.repository, storage.root)
    with restarted.worker_lock():
        assert row(restarted, "media_jobs", "id", lease.job_id)["state"] == "ready"
        assert (storage.root / "blobs" / prepared.variant.sha256).read_bytes() == VARIANT
        assert not paths.directory.exists()
        assert restarted.repository.health()["accounted_bytes"] == len(VARIANT)


def test_failed_unlink_preserves_reservation_until_real_cleanup(storage, monkeypatch):
    with storage.worker_lock():
        lease, paths, _ = staged(storage)
        real_unlink = storage._unlink
        def refuse(path):
            if path == paths.original:
                raise OSError("synthetic unlink failure")
            real_unlink(path)
        monkeypatch.setattr(storage, "_unlink", refuse)
        with pytest.raises(MediaStoreError, match="media_cleanup"):
            storage.fail(lease, "fixture_failure", retry=True)
        assert paths.original.is_file()
        job = row(storage, "media_jobs", "id", lease.job_id)
        assert job["state"] == "cleanup" and job["cleanup_state"] == "retry"
        assert storage.repository.health()["accounted_bytes"] == 2000
        monkeypatch.setattr(storage, "_unlink", real_unlink)
        storage.recover()
        assert not paths.directory.exists()
        assert row(storage, "media_jobs", "id", lease.job_id)["state"] == "retry"
        assert row(storage, "media_jobs", "id", lease.job_id)["retry_at"] == 0
        assert storage.repository.health()["accounted_bytes"] == 0


def test_partial_original_from_interrupted_worker_is_removed_before_reservation_release(storage):
    with storage.worker_lock():
        queued(storage)
        lease = storage.repository.claim_job()
        paths = storage.staging(lease)
        paths.original.write_bytes(b"partial")
    restarted = MediaStore(storage.repository, storage.root)
    with restarted.worker_lock():
        assert not paths.directory.exists()
        assert row(storage, "media_jobs", "id", lease.job_id)["state"] == "retry"
        assert restarted.repository.health()["accounted_bytes"] == 0


def test_orphan_failed_unlink_is_accounted_then_recovered(storage, monkeypatch):
    with storage.worker_lock():
        orphan = storage.root / "staging" / "unknown"
        orphan.write_bytes(b"untracked public bytes")
        real_unlink = storage._unlink
        monkeypatch.setattr(storage, "_unlink", lambda path: (_ for _ in ()).throw(OSError("unlink failure")))
        report = storage.recover()
        assert report.pending == 1
        assert storage.repository.health()["accounted_bytes"] == orphan.stat().st_size
        with storage.db.transaction() as conn:
            assert conn.execute("SELECT path FROM media_orphans").fetchone()["path"] == "staging/unknown"
        monkeypatch.setattr(storage, "_unlink", real_unlink)
        storage.recover()
        assert not orphan.exists() and storage.repository.health()["accounted_bytes"] == 0


def test_deleting_row_survives_unlink_failure_and_finishes_on_restart(storage, monkeypatch):
    with storage.worker_lock():
        lease, _, prepared = ready(storage)
        monkeypatch.setattr(storage, "_unlink", lambda _: (_ for _ in ()).throw(OSError("unlink failure")))
        assert storage.collect(target_bytes=0).removed == 0
        assert row(storage, "media_blobs", "digest", prepared.variant.sha256)["state"] == "deleting"
        assert storage.repository.health()["accounted_bytes"] == len(VARIANT)
    restarted = MediaStore(storage.repository, storage.root)
    with restarted.worker_lock():
        assert row(storage, "media_blobs", "digest", prepared.variant.sha256) is None
        assert row(storage, "media_jobs", "id", lease.job_id)["state"] == "evicted"
        assert not (storage.root / "blobs" / prepared.variant.sha256).exists()
        assert storage.repository.health()["accounted_bytes"] == 0


@pytest.mark.parametrize("secured", [False, True])
def test_exact_authorized_read_holds_transfer_pin_and_releases_on_completion(storage, registry, secured):
    with storage.worker_lock():
        _, _, prepared = ready(storage)
        player, _, _ = grant(storage, registry, prepared.variant, secured=secured)
        reader = MediaStore(
            storage.repository,
            storage.root,
            execution=PostgresExecutionRepository(),
        ).open_read(player["token"], prepared.variant.sha256)
        with storage.db.transaction() as conn:
            transfer = conn.execute("SELECT * FROM media_references WHERE owner LIKE 'transfer:%'").fetchone()
        assert transfer["expires_at"] == 1150
        with storage.repository.transaction() as conn:
            conn.execute("DELETE FROM media_references WHERE owner NOT LIKE 'transfer:%'")
        assert storage.collect(target_bytes=0).removed == 0
        with reader:
            assert reader.read(7) == VARIANT[:7]
            assert reader.read() == VARIANT[7:]
            assert reader.read() == b""
        assert storage.collect(target_bytes=0).removed == 1


@pytest.mark.parametrize("fault", ["no_reference", "expired", "wrong_variant", "rebind", "retire", "rotate_token"])
def test_new_request_requires_current_exact_authority(storage, registry, fault):
    with storage.worker_lock():
        _, _, prepared = ready(storage)
        player, key, plan = grant(storage, registry, prepared.variant)
        if fault in ("no_reference", "expired", "wrong_variant"):
            with storage.repository.transaction() as conn:
                if fault == "no_reference":
                    conn.execute("DELETE FROM media_references")
                elif fault == "expired":
                    conn.execute("UPDATE media_references SET expires_at=999")
                else:
                    manifest = plan.model_dump(mode="json")
                    manifest["layers"][0]["variant"]["width"] += 1
                    conn.execute("UPDATE plan_offers SET manifest=%s", (Jsonb(manifest),))
        elif fault == "rebind":
            other, _, _ = enroll(registry)
            registry.bind("portrait", other["player_id"], "HDMI-A-1", expected_generation=1)
        elif fault == "retire":
            registry.retire(player["player_id"])
        else:
            enroll(registry, key)
        with pytest.raises(RegistryError):
            storage.open_read(player["token"], prepared.variant.sha256)
        assert row(storage, "media_blobs", "digest", prepared.variant.sha256)["state"] == "ready"
        with storage.db.transaction() as conn:
            assert conn.execute("SELECT count(*) AS n FROM media_references WHERE owner LIKE 'transfer:%'").fetchone()["n"] == 0


def test_quota_reduction_and_corrupt_restart_preserve_secured_logical_pin(storage, registry):
    with storage.worker_lock():
        _, _, prepared = ready(storage)
        player, _, _ = grant(storage, registry, prepared.variant, secured=True)
        storage.set_quota(1)
        assert storage.collect(target_bytes=0).pressure
        canonical = storage.root / "blobs" / prepared.variant.sha256
        canonical.write_bytes(b"corrupt public bytes")
    restarted = MediaStore(
        storage.repository,
        storage.root,
        execution=PostgresExecutionRepository(),
    )
    with restarted.worker_lock():
        assert row(storage, "media_blobs", "digest", prepared.variant.sha256)["state"] == "corrupt"
        assert storage.repository.health()["accounted_bytes"] == len(VARIANT)
        assert canonical.exists()
        with pytest.raises(RegistryError):
            restarted.open_read(player["token"], prepared.variant.sha256)
        with storage.db.transaction() as conn:
            assert conn.execute("SELECT count(*) AS n FROM assignment_locks").fetchone()["n"] == 1
            assert conn.execute("SELECT count(*) AS n FROM media_references").fetchone()["n"] == 1


def test_nonsymlink_read_refuses_replaced_blob_without_reading_target(storage, registry, tmp_path):
    with storage.worker_lock():
        _, _, prepared = ready(storage)
        player, _, _ = grant(storage, registry, prepared.variant)
        canonical = storage.root / "blobs" / prepared.variant.sha256
        target = tmp_path / "outside"
        target.write_bytes(VARIANT)
        canonical.unlink()
        canonical.symlink_to(target)
        with pytest.raises(MediaStoreError):
            storage.open_read(player["token"], prepared.variant.sha256)
        assert target.read_bytes() == VARIANT
        assert row(storage, "media_blobs", "digest", prepared.variant.sha256)["state"] == "corrupt"


def test_read_timeout_closes_descriptor_before_transfer_release(storage, registry):
    with storage.worker_lock():
        _, _, prepared = ready(storage)
        player, _, _ = grant(storage, registry, prepared.variant)
        reader = storage.open_read(player["token"], prepared.variant.sha256)
        registry.clock.advance(121)
        with pytest.raises(MediaStoreError, match="media_read_timeout"):
            reader.read()
        with storage.db.transaction() as conn:
            assert conn.execute("SELECT count(*) AS n FROM media_references WHERE owner LIKE 'transfer:%'").fetchone()["n"] == 0


def test_retired_player_existing_read_finishes_but_new_read_is_refused(storage, registry):
    with storage.worker_lock():
        _, _, prepared = ready(storage)
        player, _, _ = grant(storage, registry, prepared.variant)
        with storage.open_read(player["token"], prepared.variant.sha256) as reader:
            registry.retire(player["player_id"])
            with pytest.raises(RegistryError):
                storage.open_read(player["token"], prepared.variant.sha256)
            assert reader.read() == VARIANT


def test_enlarged_corrupt_pinned_file_keeps_actual_bytes_accounted(storage, registry):
    with storage.worker_lock():
        _, _, prepared = ready(storage)
        player, _, _ = grant(storage, registry, prepared.variant, secured=True)
        canonical = storage.root / "blobs" / prepared.variant.sha256
        canonical.write_bytes(VARIANT * 100)
        with pytest.raises(MediaStoreError):
            storage.open_read(player["token"], prepared.variant.sha256)
        assert storage.repository.health()["accounted_bytes"] == len(VARIANT) * 100
        assert storage.collect(target_bytes=0).removed == 0


def test_abandoned_publishing_row_is_cleaned_instead_of_leaking_pressure(storage):
    with storage.worker_lock():
        _, _, prepared = ready(storage)
        with storage.repository.transaction() as conn:
            conn.execute("UPDATE media_jobs SET variant_sha=NULL,state='retry'")
            conn.execute("UPDATE media_blobs SET state='publishing'")
        storage.recover()
        assert row(storage, "media_blobs", "digest", prepared.variant.sha256) is None
        assert storage.repository.health()["accounted_bytes"] == 0


def test_failure_before_staging_exists_can_release_unused_reservation(storage):
    with storage.worker_lock():
        queued(storage)
        lease = storage.repository.claim_job()
        storage.fail(lease, "fixture_failure")
        assert row(storage, "media_jobs", "id", lease.job_id)["state"] == "failed"
        assert storage.repository.health()["accounted_bytes"] == 0


def test_writer_lock_is_released_by_os_after_process_death(storage):
    storage.root.mkdir()
    marker = storage.root.parent / "child-locked"
    program = (
        "import fcntl,sys,time\nfrom pathlib import Path\n"
        "with open(sys.argv[1], 'a') as stream:\n"
        " fcntl.flock(stream, fcntl.LOCK_EX)\n"
        " Path(sys.argv[2]).write_text('locked')\n"
        " time.sleep(30)\n"
    )
    child = subprocess.Popen([sys.executable, "-c", program, str(storage.root / ".worker.lock"), str(marker)])
    try:
        until = time.monotonic() + 5
        while not marker.exists() and time.monotonic() < until:
            assert child.poll() is None
            time.sleep(.01)
        assert marker.exists()
        with pytest.raises(MediaStoreError, match="writer_active"):
            with storage.worker_lock():
                pytest.fail("competing writer entered")
    finally:
        child.kill()
        child.wait(timeout=5)
    with storage.worker_lock():
        pass


def test_idle_read_timer_closes_real_descriptor_and_releases_transfer(storage, registry, monkeypatch):
    import central.media_store as module
    with storage.worker_lock():
        _, _, prepared = ready(storage)
        player, _, _ = grant(storage, registry, prepared.variant)
        monkeypatch.setattr(module, "_READ_SECONDS", 1)
        reader = storage.open_read(player["token"], prepared.variant.sha256)
        descriptor = reader._fd
        until = time.monotonic() + 3
        try:
            while time.monotonic() < until:
                try:
                    os.fstat(descriptor)
                except OSError:
                    break
                time.sleep(.02)
            else:
                pytest.fail("idle read descriptor remained open past its deadline")
        finally:
            reader.close()
        with storage.db.transaction() as conn:
            assert conn.execute("SELECT count(*) AS n FROM media_references WHERE owner LIKE 'transfer:%'").fetchone()["n"] == 0


@pytest.mark.parametrize("field", ["recipe_id", "asset_id", "original_sha1", "blob_variant"])
def test_recovery_rejects_mismatched_publication_journal(storage, monkeypatch, field):
    with storage.worker_lock():
        lease, _, prepared = staged(storage)
        monkeypatch.setattr(storage, "_rename", lambda *_: (_ for _ in ()).throw(Crash()))
        with pytest.raises(Crash):
            storage.publish(lease, prepared)
        with storage.repository.transaction() as conn:
            if field == "blob_variant":
                variant = prepared.variant.model_dump(mode="json")
                variant["width"] += 1
                conn.execute("UPDATE media_blobs SET variant=%s", (Jsonb(variant),))
            else:
                result = conn.execute("SELECT result FROM media_jobs WHERE id=%s", (lease.job_id,)).fetchone()["result"]
                result[field] = "wrong"
                conn.execute("UPDATE media_jobs SET result=%s WHERE id=%s", (Jsonb(result), lease.job_id))
    restarted = MediaStore(storage.repository, storage.root)
    with restarted.worker_lock():
        assert row(storage, "media_jobs", "id", lease.job_id)["state"] == "retry"
        assert row(storage, "media_blobs", "digest", prepared.variant.sha256) is None
        assert storage.repository.health()["accounted_bytes"] == 0
