"""Stage-one offer integration with generated bytes and no physical boot claim."""

import base64
import functools
import hashlib
import json
import time

import pytest
from test_netboot_init import (
    BODY,
    PROVENANCE,
    RECORD,
    ROOT,
    SERIAL,
    FakeClockGate,
    FakeKeeper,
    Ops,
    RecordingLog,
)
from uplink_fakes import FakeReply, central

import appliance.netboot_init as netboot
from appliance.boot_offer import read_handoff
from appliance.netboot_init import hand_over_resolver as original_hand_over_resolver
from uplink.causes import UplinkError
from uplink.origin import Origin
from uplink.transport import HOP_TIMEOUT

BOOT_ID = "11111111-2222-3333-4444-555555555555"
OFFER_ID = "12345678-1234-1234-1234-123456789abc"
SHA256 = hashlib.sha256(BODY).hexdigest()
BASE_PATH = f"/v1/netboot/offers/{OFFER_ID}/base"
ORIGIN = Origin.parse_root(ROOT)


def offer(*, sha256=SHA256, size=len(BODY)):
    return json.dumps({
        "schema": 1, "offer_id": OFFER_ID,
        "base": {"tag": "v0.13.0", "sha256": sha256, "size": size},
        "initial_app": {"tag": "v0.13.0", "sha256": "b" * 64, "size": 456},
        "initial_app_status": "selected", "compatibility_basis": "abi_match",
        "base_policy_source": "operator_baseline", "base_policy_revision": 7,
        "app_policy_source": "explicit", "app_policy_revision": 9,
        "expires_at": 1800000000.0,
    }).encode()


def base_reply(body=BODY, digest=SHA256):
    return FakeReply(200, body=body, headers={
        "Content-Length": str(len(body)),
        "Digest": "sha-256=" + base64.b64encode(bytes.fromhex(digest)).decode(),
    })


class OfferTransport:
    def __init__(self, answers):
        self.answers = answers
        self.requests = []

    def send(self, url, *, headers, deadline, status_timeout=HOP_TIMEOUT,
             method="GET", body=None):
        self.requests.append((method, str(url), body, deadline))
        answer = self.answers[(method, str(url))]
        if callable(answer):
            answer = answer()
        if isinstance(answer, Exception):
            raise answer
        return answer


def answers(*, offer_reply=None, base=None):
    return {
        ("GET", str(ORIGIN.url("/v1/locate"))): central,
        ("POST", str(ORIGIN.url("/v1/netboot/offers"))):
            offer_reply or (lambda: FakeReply(200, body=offer())),
        ("GET", str(ORIGIN.url(BASE_PATH))): base or base_reply,
        ("GET", str(ORIGIN.url("/v1/netboot/base"))): base_reply,
    }


def run(tmp_path, monkeypatch, transport, *, ops=None, keeper=None):
    resolver = tmp_path / "resolver"
    resolver.write_text("nameserver 192.0.2.1\n")
    monkeypatch.setattr(netboot, "INITRD_CA_BUNDLE", tmp_path / "missing-ca")
    monkeypatch.setattr(netboot, "hand_over_resolver",
                        functools.partial(original_hand_over_resolver, source=resolver))
    ops = ops or Ops(tmp_path)
    netboot.netboot({"photowall.central": ROOT}, tmp_path / "root", ops=ops,
                    transport=transport, clock_gate=FakeClockGate(RECORD),
                    keeper=keeper or FakeKeeper(), trust_provenance=PROVENANCE,
                    serial_reader=lambda: SERIAL, log=RecordingLog(), offer_mode=True,
                    boot_id_reader=lambda: BOOT_ID)
    return ops


def test_offer_posts_before_exact_base_and_hands_reference_to_new_root(tmp_path, monkeypatch):
    transport = OfferTransport(answers())
    ops = run(tmp_path, monkeypatch, transport)
    assert [(method, url) for method, url, _, _ in transport.requests] == [
        ("GET", str(ORIGIN.url("/v1/locate"))),
        ("POST", str(ORIGIN.url("/v1/netboot/offers"))),
        ("GET", str(ORIGIN.url(BASE_PATH))),
    ]
    body = json.loads(transport.requests[1][2])
    assert body["kernel_boot_id"] == BOOT_ID and len(body["boot_nonce"]) == 32
    handoff = read_handoff(tmp_path / "root/etc/photo-wall/boot-handoff.json")
    assert handoff["offer_id"] == OFFER_ID
    assert handoff["initial_app"]["sha256"] == "b" * 64
    assert handoff["base_digest"] == SHA256
    assert ops.mounted == [(BODY, tmp_path / "root")]


def test_same_boot_retry_reuses_nonce_even_after_failure(tmp_path, monkeypatch):
    first = OfferTransport(answers(base=lambda: FakeReply(503, body=b'{"error":"base_unavailable"}')))
    with pytest.raises(UplinkError):
        run(tmp_path, monkeypatch, first)
    (tmp_path / "run/ram").rmdir()
    second = OfferTransport(answers())
    run(tmp_path, monkeypatch, second)
    assert json.loads(first.requests[1][2])["boot_nonce"] == \
        json.loads(second.requests[1][2])["boot_nonce"]


def test_only_canonical_unknown_route_falls_back_to_legacy_base(tmp_path, monkeypatch):
    transport = OfferTransport(answers(offer_reply=lambda: FakeReply(
        404, body=b'{"detail":"Not Found"}')))
    run(tmp_path, monkeypatch, transport)
    assert transport.requests[-1][1] == str(ORIGIN.url("/v1/netboot/base"))
    assert read_handoff(tmp_path / "root/etc/photo-wall/boot-handoff.json")["mode"] == \
        "legacy_uncorrelated"


@pytest.mark.parametrize("response", [
    lambda: FakeReply(503, body=b'{"error":"recovery_required"}'),
    lambda: FakeReply(410, body=b'{"error":"boot_offer_expired"}'),
    lambda: FakeReply(404, body=b'{"error":"not_found"}'),
])
def test_named_failure_never_uses_mutable_legacy_base(tmp_path, monkeypatch, response):
    transport = OfferTransport(answers(offer_reply=response))
    with pytest.raises(UplinkError):
        run(tmp_path, monkeypatch, transport)
    assert not any(url.endswith("/v1/netboot/base") for _, url, _, _ in transport.requests)


@pytest.mark.parametrize("response", [
    lambda: FakeReply(200, body=b"not-offer-json"),
    lambda: FakeReply(200, body=offer(sha256="a" * 64)),
])
def test_invalid_offer_or_mismatched_bytes_never_mounts(tmp_path, monkeypatch, response):
    transport = OfferTransport(answers(offer_reply=response))
    ops = Ops(tmp_path)
    with pytest.raises((netboot.NetbootError, UplinkError)):
        run(tmp_path, monkeypatch, transport, ops=ops)
    assert ops.mounted == []


def test_paced_post_forwards_body_and_preserves_deadline_and_pets(tmp_path):
    transport = OfferTransport({("POST", str(ORIGIN.url("/v1/netboot/offers"))):
                                lambda: FakeReply(200, body=b"ok")})
    keeper = FakeKeeper()
    paced = netboot._PacedTransport(transport, keeper)
    before = time.monotonic()
    reply = paced.send(ORIGIN.url("/v1/netboot/offers"), headers={},
                       deadline=before + 999, method="POST", body=b"{}")
    assert transport.requests[0][:3] == ("POST", str(ORIGIN.url("/v1/netboot/offers")), b"{}")
    assert transport.requests[0][3] <= before + netboot.STAGE1_SEND_SECONDS + 1
    assert keeper.pets == 1
    assert reply.read(2, timeout=1) == b"ok" and keeper.pets == 2
    reply.close()
