-- New offer-aware bases receive only inert Player payloads. Historical schema-1
-- offers remain frozen and readable while older boot trees finish their boot.
ALTER TABLE fleet_boot_offers
    ADD COLUMN offer_sequence BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ADD COLUMN offer_schema INTEGER NOT NULL DEFAULT 1 CHECK (offer_schema IN (1, 2)),
    ADD COLUMN app_format TEXT CHECK (app_format = 'pw-player-data-v1'),
    ADD COLUMN app_base_abi TEXT CHECK (app_base_abi ~ '^sha256:[0-9a-f]{64}$'),
    ADD CONSTRAINT fleet_payload_offer_complete CHECK (
        (offer_schema = 1 AND app_format IS NULL AND app_base_abi IS NULL)
        OR
        (offer_schema = 2 AND
         ((app_status = 'selected' AND app_format IS NOT NULL AND app_base_abi IS NOT NULL)
          OR (app_status <> 'selected' AND app_format IS NULL AND app_base_abi IS NULL))));

-- Existing rows predate the sequence. Assign them a deterministic display order;
-- the identity's next value already follows the number of backfilled rows.
WITH ranked AS (
    SELECT offer_id, row_number() OVER (ORDER BY created_at, offer_id) AS n
    FROM fleet_boot_offers
)
UPDATE fleet_boot_offers AS offers SET offer_sequence = ranked.n
FROM ranked WHERE ranked.offer_id = offers.offer_id;

ALTER TABLE fleet_boot_offers ADD CONSTRAINT fleet_offer_sequence_unique UNIQUE (offer_sequence);

-- Asset preflight and GET both hash the entire opened object. Bound repeated
-- requests for a single immutable offer as well as new offer creation.
ALTER TABLE fleet_t0_daily_quotas DROP CONSTRAINT fleet_t0_daily_quotas_kind_check;
ALTER TABLE fleet_t0_daily_quotas ADD CONSTRAINT fleet_t0_daily_quotas_kind_check
    CHECK (kind IN ('offer','observation','new_device','asset'));

-- Older Central writers omit this field and therefore remain explicitly legacy.
-- New writers set it to the inert payload format. Never reinterpret stored .deb
-- digests as payload digests during a rolling rollout or rollback.
ALTER TABLE fleet_app_policy
    ADD COLUMN target_format TEXT NOT NULL DEFAULT 'player-deb'
    CHECK (target_format IN ('player-deb','pw-player-data-v1'));
ALTER TABLE fleet_device_app_overrides
    ADD COLUMN target_format TEXT NOT NULL DEFAULT 'player-deb'
    CHECK (target_format IN ('player-deb','pw-player-data-v1'));

-- An old writer updating a new payload row does not know to change target_format.
-- Reject that mixed-version write instead of leaving a falsely typed digest.
CREATE FUNCTION fleet_validate_policy_artifact() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE release_sha TEXT;
DECLARE release_size BIGINT;
BEGIN
    IF NEW.target_tag IS NOT NULL THEN
        IF NEW.target_format = 'pw-player-data-v1' THEN
            SELECT payload_sha256,payload_size INTO release_sha,release_size
            FROM app_releases WHERE tag=NEW.target_tag;
        ELSE
            SELECT asset_sha256,asset_size INTO release_sha,release_size
            FROM app_releases WHERE tag=NEW.target_tag;
        END IF;
        IF release_sha IS DISTINCT FROM NEW.target_sha256
           OR release_size IS DISTINCT FROM NEW.target_size THEN
            RAISE EXCEPTION 'fleet policy artifact format mismatch'
                USING ERRCODE='23514', CONSTRAINT='fleet_policy_artifact_format';
        END IF;
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER fleet_app_policy_artifact_guard
    BEFORE INSERT OR UPDATE ON fleet_app_policy
    FOR EACH ROW EXECUTE FUNCTION fleet_validate_policy_artifact();
CREATE TRIGGER fleet_device_override_artifact_guard
    BEFORE INSERT OR UPDATE ON fleet_device_app_overrides
    FOR EACH ROW EXECUTE FUNCTION fleet_validate_policy_artifact();
