-- Schema-2 app evidence is an optional observation, never an acceptance record.
-- Existing and old-writer rows retain schema 1 and project unknown app facts.
ALTER TABLE fleet_os_observations
    ADD COLUMN arrival_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ADD COLUMN observation_schema SMALLINT NOT NULL DEFAULT 1
        CHECK (observation_schema IN (1, 2)),
    ADD COLUMN app_installed_sha256 TEXT
        CHECK (app_installed_sha256 ~ '^[0-9a-f]{64}$'),
    ADD COLUMN app_running_sha256 TEXT
        CHECK (app_running_sha256 ~ '^[0-9a-f]{64}$'),
    ADD COLUMN app_running_pid INTEGER CHECK (app_running_pid > 0),
    ADD COLUMN app_running_start_ticks BIGINT CHECK (app_running_start_ticks > 0),
    ADD COLUMN app_running_invocation_id TEXT
        CHECK (app_running_invocation_id ~ '^[0-9a-f]{32}$'),
    ADD COLUMN app_installed_reason TEXT
        CHECK (app_installed_reason ~ '^[a-z0-9_]{1,64}$'),
    ADD COLUMN app_running_reason TEXT
        CHECK (app_running_reason ~ '^[a-z0-9_]{1,64}$'),
    ADD CONSTRAINT fleet_app_observation_coherent CHECK (
        (observation_schema = 1 AND app_installed_sha256 IS NULL
            AND app_running_sha256 IS NULL AND app_running_pid IS NULL
            AND app_running_start_ticks IS NULL AND app_running_invocation_id IS NULL
            AND app_installed_reason IS NULL AND app_running_reason IS NULL)
        OR (observation_schema = 2
            AND ((app_installed_sha256 IS NULL) <> (app_installed_reason IS NULL))
            AND ((app_running_sha256 IS NULL) <> (app_running_reason IS NULL))
            AND (app_running_sha256 IS NULL OR (
                app_installed_sha256 IS NOT NULL
                AND app_running_sha256 = app_installed_sha256
                AND app_running_pid IS NOT NULL AND app_running_start_ticks IS NOT NULL
                AND app_running_invocation_id IS NOT NULL))
            AND (app_running_sha256 IS NOT NULL OR (
                app_running_pid IS NULL AND app_running_start_ticks IS NULL
                AND app_running_invocation_id IS NULL)))
    );
